<?php

namespace App\Services;

use App\Models\SmsQueue;
use App\Services\ItexmoSmsService;
use Carbon\Carbon;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class SmsQueueService
{
    /**
     * How many times a single queue row may be picked up before it is left alone.
     *
     * A row is claimed BEFORE the provider call, so a worker that dies mid-send leaves it 'pending'
     * with its attempt already counted. Without a ceiling that row would be retried on every tick
     * forever, and a message that reliably crashes the worker would block the queue behind it.
     */
    protected const MAX_ATTEMPTS = 3;

    /** Tag every line of the run log carries, mirroring AutoDisconnectService. */
    private string $logName = 'SMS_Queue';

    protected ItexmoSmsService $smsService;

    public function __construct(ItexmoSmsService $smsService)
    {
        $this->smsService = $smsService;
    }

    /**
     * Queue one SMS, at most once.
     *
     * Scheduled notices are generated by scans that are expected to re-run — daily crons, manual
     * re-runs, a scan whose "already notified" marker failed to persist. Queueing is therefore
     * idempotent for anything carrying a `time_sent`: the (account, contact, message, time_sent)
     * tuple is hashed into `sms_queue.dedupe_key`, which is UNIQUE, so the second insert loses at
     * the database and the row already queued is returned instead. Two overlapping runs cannot
     * text a customer twice.
     *
     * Messages queued WITHOUT a time_sent are deliberately NOT deduplicated (see the migration):
     * sending the same message to the same customer twice by hand is a legitimate operator action.
     *
     * @return SmsQueue the row queued, or the one already queued for this exact notification
     */
    public function queueSms(array $data): SmsQueue
    {
        $accountNo = $data['account_no'] ?? null;
        $contactNo = $data['contact_no'];
        $message   = $data['message'];
        $timeSent  = $data['time_sent'] ?? null;

        $dedupeKey = $this->dedupeKeyFor($accountNo, $contactNo, $message, $timeSent);

        if ($dedupeKey !== null) {
            $existing = SmsQueue::where('dedupe_key', $dedupeKey)->first();

            if ($existing) {
                Log::info('SMS already queued for this notification, not queueing again', [
                    'account_no' => $accountNo,
                    'sms_queue_id' => $existing->id,
                    'status' => $existing->status,
                    'time_sent' => $timeSent,
                ]);

                return $existing;
            }
        }

        try {
            return SmsQueue::create([
                'account_no' => $accountNo,
                'contact_no' => $contactNo,
                'message' => $message,
                'status' => 'pending',
                'time_sent' => $timeSent,
                'dedupe_key' => $dedupeKey,
            ]);
        } catch (QueryException $e) {
            // Lost the race against a concurrent run holding the same dedupe_key. That run has
            // already queued the message, so this is success, not failure. Any other query error
            // is a real problem and is re-thrown for the caller to report.
            if ($dedupeKey !== null && $this->isDuplicateKeyViolation($e)) {
                $existing = SmsQueue::where('dedupe_key', $dedupeKey)->first();

                if ($existing) {
                    Log::info('SMS queued concurrently by another run, reusing that row', [
                        'account_no' => $accountNo,
                        'sms_queue_id' => $existing->id,
                    ]);

                    return $existing;
                }
            }

            Log::error('Failed to queue SMS', [
                'account_no' => $accountNo,
                'error' => $e->getMessage(),
            ]);

            throw $e;
        }
    }

    /**
     * The idempotency key for a scheduled notification, or null when the message is not one.
     *
     * MUST stay in step with the UNIQUE index added in
     * 2026_08_06_000002_add_dedupe_key_to_sms_queue.
     */
    public function dedupeKeyFor(?string $accountNo, string $contactNo, string $message, ?string $timeSent): ?string
    {
        if (empty($timeSent)) {
            return null;
        }

        return hash('sha256', implode("\0", [
            (string) $accountNo,
            $contactNo,
            $message,
            $timeSent,
        ]));
    }

    /**
     * Send the SMS that are due now.
     *
     * Each row is CLAIMED with a conditional update before the provider is called: the update only
     * matches while the row is still 'pending' and still carries the attempt count that was read,
     * so a second worker running against the same batch — an overlapping cron tick, or the
     * standalone command run by hand while the scheduler is also running — comes away with zero
     * affected rows and skips it. Without the claim both workers would call the provider and the
     * customer would get the message twice.
     */
    public function processPendingSms(int $batchSize = 50): array
    {
        $jobs = SmsQueue::pending()
            ->where('attempts', '<', self::MAX_ATTEMPTS)
            ->orderBy('created_at', 'asc')
            ->limit($batchSize)
            ->get();

        if ($jobs->isEmpty()) {
            // Deliberately silent. This runs inside cron:process-email-queue, every minute —
            // banner-logging an empty queue would bury the real runs under ~1,400 lines a day.
            return [
                'processed' => 0,
                'sent' => 0,
                'failed' => 0,
                'skipped' => 0,
            ];
        }

        $logFile = 'sms_queue_' . Carbon::now()->format('Y-m-d') . '.log';
        $log = fn (string $message) => $this->writeLog($message, $logFile);
        $startTime = Carbon::now();

        $log("");
        $log("╔════════════════════════════════════════════════════════════════╗");
        $log("║              STARTING SMS QUEUE PROCESSING                     ║");
        $log("╚════════════════════════════════════════════════════════════════╝");
        $log("Start Time: " . $startTime->format('Y-m-d H:i:s'));
        $log("Gateway   : " . $this->smsService->describeActiveConfig());
        $log("Pending   : {$jobs->count()} message(s), batch size {$batchSize}, max attempts " . self::MAX_ATTEMPTS);
        $log("");

        Log::info('Processing SMS queue', ['count' => $jobs->count()]);

        $stats = [
            'processed' => 0,
            'sent' => 0,
            'failed' => 0,
            'skipped' => 0,
        ];

        foreach ($jobs as $job) {
            $attemptsAtRead = (int) $job->attempts;

            $claimed = SmsQueue::where('id', $job->id)
                ->where('status', 'pending')
                ->where('attempts', $attemptsAtRead)
                ->update([
                    'attempts' => $attemptsAtRead + 1,
                    'updated_at' => now(),
                ]);

            if ($claimed === 0) {
                // Another worker took this row between the read and the claim.
                $stats['skipped']++;
                $log("[SKIP] Queue #{$job->id} - claimed by another worker");
                continue;
            }

            $stats['processed']++;
            $job->attempts = $attemptsAtRead + 1;

            $result = $this->smsService->send([
                'contact_no' => $job->contact_no,
                'message' => $job->message,
                // Carried through so sms_logs records which account the message belonged to —
                // without it every queued message logs against a NULL account and cannot be traced.
                'account_no' => $job->account_no,
                'source' => 'sms_queue',
                'reference_id' => (string) $job->id,
            ]);

            // The gateway itself cannot send — an empty balance, a disabled account. Marking this
            // row failed and moving on would walk the whole batch into 'failed' at one attempt
            // each, for a reason that has nothing to do with any of the messages. Give the claim
            // back instead and stop: the rows stay pending, with their attempts intact, and go out
            // on the next run once the account can send again.
            if (!empty($result['account_blocked'])) {
                SmsQueue::where('id', $job->id)
                    ->where('attempts', $attemptsAtRead + 1)
                    ->update(['attempts' => $attemptsAtRead, 'updated_at' => now()]);

                $stats['processed']--;
                $stats['aborted'] = true;
                $stats['abort_reason'] = $result['error'] ?? 'gateway unavailable';

                $log("");
                $log("[ABORT] Gateway cannot send - run stopped, remaining messages left pending");
                $log("        Reason: " . $stats['abort_reason']);
                Log::error('SMS queue run aborted: gateway cannot send', [
                    'id' => $job->id,
                    'error' => $stats['abort_reason'],
                ]);

                break;
            }

            if ($result['success']) {
                $job->markAsSent();
                $stats['sent']++;
                $log("[SENT] Queue #{$job->id} - Account: {$job->account_no} - To: {$job->contact_no}");
                Log::info('SMS sent from queue', ['id' => $job->id, 'account_no' => $job->account_no]);
            } else {
                $error = $result['error'] ?? 'Unknown error';
                $job->markAsFailed($error);
                $stats['failed']++;
                $log("[FAIL] Queue #{$job->id} - Account: {$job->account_no} - To: {$job->contact_no} - Attempt {$job->attempts}/" . self::MAX_ATTEMPTS);
                $log("       Reason: {$error}");
                Log::error('SMS failed from queue', [
                    'id' => $job->id,
                    'account_no' => $job->account_no,
                    'attempts' => $job->attempts,
                    'error' => $error,
                ]);
            }

            // Small delay to avoid hitting API rate limits too hard
            usleep(200000);
        }

        $endTime = Carbon::now();
        $log("");
        $log("Processed : {$stats['processed']}  Sent: {$stats['sent']}  Failed: {$stats['failed']}  Skipped: {$stats['skipped']}");
        if (!empty($stats['aborted'])) {
            $log("Status    : ABORTED - messages left pending for the next run");
        }
        $log("End Time  : " . $endTime->format('Y-m-d H:i:s') . " (" . $startTime->diffInSeconds($endTime) . "s)");
        $log("╚════════════════════════════════════════════════════════════════╝");

        return $stats;
    }

    /**
     * Append one line to the SMS queue run log.
     *
     * Mirrors AutoDisconnectService::writeLog: its own dated file under storage/logs/smsqueue, plus
     * a copy on the default channel. The queue previously reported only aggregate counts into the
     * shared emailqueue log, so a failing send left no record of which number or which reason.
     *
     * @param string $fileName Log file to append to, relative to storage/logs/smsqueue.
     */
    private function writeLog(string $message, string $fileName = 'sms_queue.log'): void
    {
        $timestamp = Carbon::now()->format('Y-m-d H:i:s');
        $logMessage = "[{$timestamp}] [{$this->logName}] {$message}";

        $logDir = storage_path('logs/smsqueue');
        $logFile = $logDir . '/' . $fileName;

        if (!file_exists($logDir)) {
            mkdir($logDir, 0755, true);
        }

        file_put_contents($logFile, $logMessage . PHP_EOL, FILE_APPEND);

        Log::channel('single')->info("[{$this->logName}] {$message}");
    }

    /**
     * A UNIQUE constraint violation, as opposed to any other query failure.
     *
     * Matched on SQLSTATE 23000 plus the driver code so a connection error or a missing column is
     * never mistaken for "already queued".
     */
    private function isDuplicateKeyViolation(QueryException $e): bool
    {
        return ($e->errorInfo[0] ?? null) === '23000'
            && in_array((int) ($e->errorInfo[1] ?? 0), [1062, 1586], true);
    }
}
