<?php

namespace App\Services;

use App\Models\SmsQueue;
use App\Services\ItexmoSmsService;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class SmsQueueService
{
    /**
     * How many times a single queue row may be picked up before it is left alone.
     *
     * A row is claimed BEFORE the provider call, so a worker that dies mid-send leaves it 'pending'
     * with its attempt already counted. Without a ceiling that row would be retried on every tick
     * forever, and a message that reliably crashes the worker would block the queue behind it.
     */
    protected const MAX_ATTEMPTS = 3;

    /**
     * Rows per INSERT when a blast is queued.
     *
     * A blast to every subscriber is tens of thousands of rows. One statement for the lot builds a
     * packet large enough to trip max_allowed_packet and writes a single enormous binlog event;
     * chunking keeps each statement short and bounded.
     */
    protected const INSERT_CHUNK = 500;

    protected ItexmoSmsService $smsService;

    public function __construct(ItexmoSmsService $smsService)
    {
        $this->smsService = $smsService;
    }

    /**
     * Queue one SMS, at most once.
     *
     * Scheduled notices are generated by scans that are expected to re-run — daily crons, manual
     * re-runs, a scan whose "already notified" marker failed to persist. Queueing is therefore
     * idempotent for anything carrying a `time_sent`: the (account, contact, message, time_sent)
     * tuple is hashed into `sms_queue.dedupe_key`, which is UNIQUE, so the second insert loses at
     * the database and the row already queued is returned instead. Two overlapping runs cannot
     * text a customer twice.
     *
     * Messages queued WITHOUT a time_sent are deliberately NOT deduplicated (see the migration):
     * sending the same message to the same customer twice by hand is a legitimate operator action.
     *
     * @return SmsQueue the row queued, or the one already queued for this exact notification
     */
    public function queueSms(array $data): SmsQueue
    {
        $accountNo = $data['account_no'] ?? null;
        $contactNo = $data['contact_no'];
        $message   = $data['message'];
        $timeSent  = $data['time_sent'] ?? null;

        $dedupeKey = $this->dedupeKeyFor($accountNo, $contactNo, $message, $timeSent);

        if ($dedupeKey !== null) {
            $existing = SmsQueue::where('dedupe_key', $dedupeKey)->first();

            if ($existing) {
                Log::info('SMS already queued for this notification, not queueing again', [
                    'account_no' => $accountNo,
                    'sms_queue_id' => $existing->id,
                    'status' => $existing->status,
                    'time_sent' => $timeSent,
                ]);

                return $existing;
            }
        }

        try {
            return SmsQueue::create([
                'account_no' => $accountNo,
                'contact_no' => $contactNo,
                'message' => $message,
                'status' => 'pending',
                'time_sent' => $timeSent,
                'dedupe_key' => $dedupeKey,
                'source' => $data['source'] ?? null,
                'reference_id' => $data['reference_id'] ?? null,
            ]);
        } catch (QueryException $e) {
            // Lost the race against a concurrent run holding the same dedupe_key. That run has
            // already queued the message, so this is success, not failure. Any other query error
            // is a real problem and is re-thrown for the caller to report.
            if ($dedupeKey !== null && $this->isDuplicateKeyViolation($e)) {
                $existing = SmsQueue::where('dedupe_key', $dedupeKey)->first();

                if ($existing) {
                    Log::info('SMS queued concurrently by another run, reusing that row', [
                        'account_no' => $accountNo,
                        'sms_queue_id' => $existing->id,
                    ]);

                    return $existing;
                }
            }

            Log::error('Failed to queue SMS', [
                'account_no' => $accountNo,
                'error' => $e->getMessage(),
            ]);

            throw $e;
        }
    }

    /**
     * Queue one SMS blast for background delivery, at most once per recipient.
     *
     * This is what replaced the provider loop that used to run inside the request. A blast to a
     * populated LCPNAP is hundreds of subscribers, each one an HTTP round trip to iTexMo taking a
     * second or more; the browser gave up long before the loop did, and the failure surfaced as a
     * CORS error because a timed-out response carries no CORS headers at all. Nothing here talks to
     * the provider — the rows are written, the request ends, and the cron worker sends them.
     *
     * Every row carries a dedupe_key over (blast, account, contact), so the batch is safe to write
     * twice: a retried request, or a second call for the same blast, inserts nothing the first one
     * already wrote. INSERT IGNORE settles that at the database rather than by reading first, which
     * two concurrent requests could both pass.
     *
     * @param  iterable  $recipients  rows carrying contact_no and account_no
     * @return int  rows newly queued — below the recipient count when some were already queued
     */
    public function queueBlast(int $blastId, iterable $recipients, string $message): int
    {
        $now = now();
        $queued = 0;
        $chunk = [];
        $seen = [];

        foreach ($recipients as $recipient) {
            $contactNo = trim((string) ($recipient->contact_no ?? ''));

            if ($contactNo === '') {
                continue;
            }

            $accountNo = $recipient->account_no ?? null;
            $dedupeKey = $this->blastDedupeKeyFor($blastId, $accountNo, $contactNo);

            // An account can carry more than one row in the recipient query — a second technical
            // details row, say. INSERT IGNORE would drop the repeat anyway; dropping it here keeps
            // the returned count honest about how many subscribers are actually being texted.
            if (isset($seen[$dedupeKey])) {
                continue;
            }
            $seen[$dedupeKey] = true;

            $chunk[] = [
                'account_no' => $accountNo,
                'contact_no' => $contactNo,
                // Substituted per recipient, exactly as the synchronous loop did.
                'message' => str_replace('{{account_no}}', (string) ($accountNo ?? ''), $message),
                'dedupe_key' => $dedupeKey,
                'source' => 'sms_blast',
                'reference_id' => (string) $blastId,
                'status' => 'pending',
                // Left NULL so the worker picks the row up on its next tick; scopePending() treats
                // a NULL time_sent as due now.
                'time_sent' => null,
                'attempts' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ];

            if (count($chunk) >= self::INSERT_CHUNK) {
                $queued += DB::table('sms_queue')->insertOrIgnore($chunk);
                $chunk = [];
            }
        }

        if ($chunk !== []) {
            $queued += DB::table('sms_queue')->insertOrIgnore($chunk);
        }

        Log::info('SMS blast queued', [
            'blast_id' => $blastId,
            'queued' => $queued,
            'recipients' => count($seen),
        ]);

        return $queued;
    }

    /**
     * The idempotency key for a scheduled notification, or null when the message is not one.
     *
     * MUST stay in step with the UNIQUE index added in
     * 2026_09_08_000001_add_dedupe_key_to_sms_queue.
     */
    public function dedupeKeyFor(?string $accountNo, string $contactNo, string $message, ?string $timeSent): ?string
    {
        if (empty($timeSent)) {
            return null;
        }

        return hash('sha256', implode("\0", [
            (string) $accountNo,
            $contactNo,
            $message,
            $timeSent,
        ]));
    }

    /**
     * The idempotency key for one recipient of one blast.
     *
     * Always non-null, unlike dedupeKeyFor(): a blast row IS replayable by construction, because
     * the controller may write the batch again for a request that was retried. The message is
     * deliberately not part of the key — a blast is identified by its id, and hashing the text too
     * would let a corrected message re-text everyone under the same blast.
     */
    public function blastDedupeKeyFor(int $blastId, ?string $accountNo, string $contactNo): string
    {
        return hash('sha256', implode("\0", [
            'sms_blast',
            (string) $blastId,
            (string) $accountNo,
            $contactNo,
        ]));
    }

    /**
     * Send the SMS that are due now.
     *
     * Each row is CLAIMED with a conditional update before the provider is called: the update only
     * matches while the row is still 'pending' and still carries the attempt count that was read,
     * so a second worker running against the same batch — an overlapping cron tick, or the
     * standalone command run by hand while the scheduler is also running — comes away with zero
     * affected rows and skips it. Without the claim both workers would call the provider and the
     * customer would get the message twice.
     */
    public function processPendingSms(int $batchSize = 50): array
    {
        $jobs = SmsQueue::pending()
            ->where('attempts', '<', self::MAX_ATTEMPTS)
            ->orderBy('created_at', 'asc')
            ->limit($batchSize)
            ->get();

        if ($jobs->isEmpty()) {
            return [
                'processed' => 0,
                'sent' => 0,
                'failed' => 0,
                'skipped' => 0,
            ];
        }

        Log::info('Processing SMS queue', ['count' => $jobs->count()]);

        $stats = [
            'processed' => 0,
            'sent' => 0,
            'failed' => 0,
            'skipped' => 0,
        ];

        foreach ($jobs as $job) {
            $attemptsAtRead = (int) $job->attempts;

            $claimed = SmsQueue::where('id', $job->id)
                ->where('status', 'pending')
                ->where('attempts', $attemptsAtRead)
                ->update([
                    'attempts' => $attemptsAtRead + 1,
                    'updated_at' => now(),
                ]);

            if ($claimed === 0) {
                // Another worker took this row between the read and the claim.
                $stats['skipped']++;
                continue;
            }

            $stats['processed']++;
            $job->attempts = $attemptsAtRead + 1;

            $result = $this->smsService->send([
                'contact_no' => $job->contact_no,
                'message' => $job->message,
                // Carried through so sms_logs records which account the message belonged to —
                // without it every queued message logs against a NULL account and cannot be traced.
                'account_no' => $job->account_no,
                'source' => $job->source ?: 'sms_queue',
                'reference_id' => $job->reference_id ?: (string) $job->id,
            ]);

            if ($result['success']) {
                $job->markAsSent();
                $stats['sent']++;
                Log::info('SMS sent from queue', [
                    'id' => $job->id,
                    'account_no' => $job->account_no,
                    'source' => $job->source,
                    'reference_id' => $job->reference_id,
                ]);
            } else {
                $job->markAsFailed($result['error'] ?? 'Unknown error');
                $stats['failed']++;
                Log::error('SMS failed from queue', [
                    'id' => $job->id,
                    'account_no' => $job->account_no,
                    'source' => $job->source,
                    'reference_id' => $job->reference_id,
                    'attempts' => $job->attempts,
                    // The provider's own words — "No SMS Balance", "Invalid ApiCode/Credentials" —
                    // rather than a generic retry count. ItexmoSmsService translates the gateway's
                    // numeric codes so this line is the one an operator can actually act on.
                    'error' => $result['error'] ?? 'Unknown error',
                ]);
            }

            // Small delay to avoid hitting API rate limits too hard
            usleep(200000);
        }

        return $stats;
    }

    /**
     * A UNIQUE constraint violation, as opposed to any other query failure.
     *
     * Matched on SQLSTATE 23000 plus the driver code so a connection error or a missing column is
     * never mistaken for "already queued".
     */
    private function isDuplicateKeyViolation(QueryException $e): bool
    {
        return ($e->errorInfo[0] ?? null) === '23000'
            && in_array((int) ($e->errorInfo[1] ?? 0), [1062, 1586], true);
    }
}
